// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:078ff5be-a79a-466b-a3f0-819dc8513106",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_2VU0SFULO",
    "aws_user_pools_web_client_id": "6jsjocic1fgs83qsodqq8fg0ih",
    "oauth": {
        "domain": "readmore-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/callback",
        "redirectSignOut": "http://localhost:3000/logout",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
